-- Acuity Gateway — SQLite schema
--
-- The two concerns are kept PHYSICALLY SEPARATE (spec #21) because they have
-- opposite needs:
--   • availability_cache  → non-PII slot data, grows freely, no retention
--   • pending_bookings    → PII, minimal residency, purged per spec #19–#22
-- Plus supporting tables for reconciliation, audit, and sync state.
--
-- All DDL is idempotent (IF NOT EXISTS) so it can run on every boot.

-- ── Availability cache (NON-PII) ────────────────────────────────────
-- A rolling forward window of open slots. Used to render the portal and to
-- keep taking bookings while Acuity is offline.
CREATE TABLE IF NOT EXISTS availability_cache (
  id                  INTEGER PRIMARY KEY AUTOINCREMENT,
  appointment_type_id TEXT    NOT NULL,          -- Acuity UUID
  calendar_id         TEXT    NOT NULL DEFAULT '', -- practitioner UUID or '' (none)
  slot_datetime       TEXT    NOT NULL,          -- ISO 8601 with offset
  slot_date           TEXT    NOT NULL,          -- YYYY-MM-DD (window pruning)
  duration_minutes    INTEGER,
  is_available        INTEGER NOT NULL DEFAULT 1, -- 0 once booked
  source              TEXT    NOT NULL DEFAULT 'acuity', -- acuity | gateway
  last_refreshed_at   TEXT    NOT NULL,
  UNIQUE (appointment_type_id, calendar_id, slot_datetime)
);
CREATE INDEX IF NOT EXISTS idx_avail_lookup ON availability_cache (appointment_type_id, slot_date);
CREATE INDEX IF NOT EXISTS idx_avail_date   ON availability_cache (slot_date);

-- ── Pending bookings (PII — minimal residency) ──────────────────────
-- Holds patient details only until the booking is confirmed synced to Acuity
-- and the appointment has passed (then the purge job removes it). Un-synced
-- rows are the outage-recovery queue and are NEVER purged by age (spec #20).
CREATE TABLE IF NOT EXISTS pending_bookings (
  id                    TEXT PRIMARY KEY,         -- uuid generated by Gateway
  acuity_appointment_id TEXT,                     -- Acuity UUID; null until synced
  appointment_type_id   TEXT NOT NULL,            -- Acuity UUID
  calendar_id           TEXT,                     -- practitioner UUID or '' (none)
  appointment_datetime  TEXT    NOT NULL,         -- ISO 8601
  appointment_date      TEXT    NOT NULL,         -- YYYY-MM-DD (purge rule)
  -- patient PII
  first_name            TEXT,
  last_name             TEXT,
  phone                 TEXT,
  email                 TEXT,
  address               TEXT,
  city                  TEXT,
  state                 TEXT,
  postcode              TEXT,
  notes                 TEXT,
  is_new_patient        INTEGER NOT NULL DEFAULT 0,
  -- lifecycle
  status                TEXT    NOT NULL DEFAULT 'pending', -- pending|confirmed|cancelled
  -- sync metadata (drives reconciliation #7 and purge #22)
  synced                INTEGER NOT NULL DEFAULT 0,
  sync_version          INTEGER NOT NULL DEFAULT 0,
  sync_attempts         INTEGER NOT NULL DEFAULT 0,
  last_attempt_at       TEXT,
  synced_at             TEXT,
  sync_error            TEXT,
  -- SMS day-before reminder bookkeeping (set once a reminder is attempted, so the
  -- daily reminder job never double-sends). Null = not yet reminded.
  reminder_sent_at      TEXT,
  created_at            TEXT    NOT NULL,
  updated_at            TEXT    NOT NULL
);
-- queue = unsynced bookings (outage recovery)
CREATE INDEX IF NOT EXISTS idx_pending_queue  ON pending_bookings (synced, last_attempt_at);
-- purge scan: synced == 1 AND appointment_date passed (spec #19)
CREATE INDEX IF NOT EXISTS idx_pending_purge  ON pending_bookings (synced, appointment_date);
CREATE INDEX IF NOT EXISTS idx_pending_acuity ON pending_bookings (acuity_appointment_id);

-- ── Reconciliation flags (surfaced in /admin for a human — spec #7) ─
CREATE TABLE IF NOT EXISTS reconciliation_flags (
  id                    INTEGER PRIMARY KEY AUTOINCREMENT,
  kind                  TEXT NOT NULL,            -- collision | orphan | mismatch
  pending_booking_id    TEXT,
  acuity_appointment_id TEXT,
  slot_datetime         TEXT,
  detail                TEXT,                     -- JSON
  status                TEXT NOT NULL DEFAULT 'open', -- open | resolved
  created_at            TEXT NOT NULL,
  resolved_at           TEXT,
  resolved_by           TEXT
);
CREATE INDEX IF NOT EXISTS idx_recon_status ON reconciliation_flags (status);

-- ── Audit log (admin access + system events — spec #17/#22) ─────────
CREATE TABLE IF NOT EXISTS audit_log (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  ts          TEXT NOT NULL,
  event_type  TEXT NOT NULL,    -- admin_login | purge | sync | webhook | error | booking
  actor       TEXT,             -- admin | system | acuity | patient
  ip          TEXT,
  success     INTEGER,
  detail      TEXT              -- JSON
);
CREATE INDEX IF NOT EXISTS idx_audit_ts   ON audit_log (ts);
CREATE INDEX IF NOT EXISTS idx_audit_type ON audit_log (event_type);

-- ── SMS log (Cellcast send + inbound/DLR — spec #14/#16) ────────────
-- Recipient phone AND message body are PII; the nightly purge job trims rows
-- older than the configured SMS retention window.
CREATE TABLE IF NOT EXISTS sms_log (
  id            INTEGER PRIMARY KEY AUTOINCREMENT,
  direction     TEXT NOT NULL,   -- outbound | inbound | dlr
  recipient     TEXT,            -- destination (outbound) or sender (inbound), E.164
  status        TEXT,            -- queued | sent | delivered | failed | received | skipped
  provider_id   TEXT,            -- Cellcast message id (idempotency + DLR correlation)
  booking_id    TEXT,            -- optional link to pending_bookings.id
  body          TEXT,            -- message text (PII; trimmed by the sms_log purge)
  intent        TEXT,            -- parsed inbound intent: confirm|cancel|stop|unknown
  action_status TEXT,            -- inbound needing staff: open|handled (null = no action)
  handled_at    TEXT,
  handled_by    TEXT,
  error         TEXT,
  created_at    TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_sms_status   ON sms_log (status);
CREATE INDEX IF NOT EXISTS idx_sms_created  ON sms_log (created_at);
-- Inbound idempotency lookup + DLR-to-outbound correlation (Cellcast retries).
CREATE INDEX IF NOT EXISTS idx_sms_provider ON sms_log (provider_id);
-- NOTE: indexes on the columns added above (e.g. action_status) live in
-- db/index.js ensureIndexes(), which runs AFTER the ADD COLUMN migration — an
-- existing DB won't have the column yet when this file is first re-applied.

-- ── SMS opt-out / suppression (compliance — APP 11, ACMA) ───────────
-- A STOP reply (or a manual admin opt-out) lands here. Checked before EVERY
-- outbound send. EXEMPT from the retention purge — an opt-out must persist.
CREATE TABLE IF NOT EXISTS sms_suppressions (
  number      TEXT PRIMARY KEY,   -- E.164 normalized
  reason      TEXT,               -- stop_reply | manual
  created_at  TEXT NOT NULL,
  created_by  TEXT                -- patient | admin
);

-- ── System state (key/value: connection health, sync cursors) ───────
CREATE TABLE IF NOT EXISTS system_state (
  key        TEXT PRIMARY KEY,
  value      TEXT,
  updated_at TEXT NOT NULL
);
