-- Acuity Gateway — SQLite schema
--
-- The two concerns are kept PHYSICALLY SEPARATE (spec #21) because they have
-- opposite needs:
--   • availability_cache  → non-PII slot data, grows freely, no retention
--   • pending_bookings    → PII, minimal residency, purged per spec #19–#22
-- Plus supporting tables for reconciliation, audit, and sync state.
--
-- All DDL is idempotent (IF NOT EXISTS) so it can run on every boot.

-- ── Availability cache (NON-PII) ────────────────────────────────────
-- A rolling forward window of open slots. Used to render the portal and to
-- keep taking bookings while Acuity is offline.
CREATE TABLE IF NOT EXISTS availability_cache (
  id                  INTEGER PRIMARY KEY AUTOINCREMENT,
  appointment_type_id INTEGER NOT NULL,
  calendar_id         INTEGER,
  slot_datetime       TEXT    NOT NULL,          -- ISO 8601 with offset
  slot_date           TEXT    NOT NULL,          -- YYYY-MM-DD (window pruning)
  duration_minutes    INTEGER,
  is_available        INTEGER NOT NULL DEFAULT 1, -- 0 once booked
  source              TEXT    NOT NULL DEFAULT 'acuity', -- acuity | gateway
  last_refreshed_at   TEXT    NOT NULL,
  UNIQUE (appointment_type_id, calendar_id, slot_datetime)
);
CREATE INDEX IF NOT EXISTS idx_avail_lookup ON availability_cache (appointment_type_id, slot_date);
CREATE INDEX IF NOT EXISTS idx_avail_date   ON availability_cache (slot_date);

-- ── Pending bookings (PII — minimal residency) ──────────────────────
-- Holds patient details only until the booking is confirmed synced to Acuity
-- and the appointment has passed (then the purge job removes it). Un-synced
-- rows are the outage-recovery queue and are NEVER purged by age (spec #20).
CREATE TABLE IF NOT EXISTS pending_bookings (
  id                    TEXT PRIMARY KEY,         -- uuid generated by Gateway
  acuity_appointment_id INTEGER,                  -- null until synced
  appointment_type_id   INTEGER NOT NULL,
  calendar_id           INTEGER,
  appointment_datetime  TEXT    NOT NULL,         -- ISO 8601
  appointment_date      TEXT    NOT NULL,         -- YYYY-MM-DD (purge rule)
  -- patient PII
  first_name            TEXT,
  last_name             TEXT,
  phone                 TEXT,
  email                 TEXT,
  address               TEXT,
  city                  TEXT,
  state                 TEXT,
  postcode              TEXT,
  notes                 TEXT,
  is_new_patient        INTEGER NOT NULL DEFAULT 0,
  -- lifecycle
  status                TEXT    NOT NULL DEFAULT 'pending', -- pending|confirmed|cancelled
  -- sync metadata (drives reconciliation #7 and purge #22)
  synced                INTEGER NOT NULL DEFAULT 0,
  sync_version          INTEGER NOT NULL DEFAULT 0,
  sync_attempts         INTEGER NOT NULL DEFAULT 0,
  last_attempt_at       TEXT,
  synced_at             TEXT,
  sync_error            TEXT,
  created_at            TEXT    NOT NULL,
  updated_at            TEXT    NOT NULL
);
-- queue = unsynced bookings (outage recovery)
CREATE INDEX IF NOT EXISTS idx_pending_queue  ON pending_bookings (synced, last_attempt_at);
-- purge scan: synced == 1 AND appointment_date passed (spec #19)
CREATE INDEX IF NOT EXISTS idx_pending_purge  ON pending_bookings (synced, appointment_date);
CREATE INDEX IF NOT EXISTS idx_pending_acuity ON pending_bookings (acuity_appointment_id);

-- ── Reconciliation flags (surfaced in /admin for a human — spec #7) ─
CREATE TABLE IF NOT EXISTS reconciliation_flags (
  id                    INTEGER PRIMARY KEY AUTOINCREMENT,
  kind                  TEXT NOT NULL,            -- collision | orphan | mismatch
  pending_booking_id    TEXT,
  acuity_appointment_id INTEGER,
  slot_datetime         TEXT,
  detail                TEXT,                     -- JSON
  status                TEXT NOT NULL DEFAULT 'open', -- open | resolved
  created_at            TEXT NOT NULL,
  resolved_at           TEXT,
  resolved_by           TEXT
);
CREATE INDEX IF NOT EXISTS idx_recon_status ON reconciliation_flags (status);

-- ── Audit log (admin access + system events — spec #17/#22) ─────────
CREATE TABLE IF NOT EXISTS audit_log (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  ts          TEXT NOT NULL,
  event_type  TEXT NOT NULL,    -- admin_login | purge | sync | webhook | error | booking
  actor       TEXT,             -- admin | system | acuity | patient
  ip          TEXT,
  success     INTEGER,
  detail      TEXT              -- JSON
);
CREATE INDEX IF NOT EXISTS idx_audit_ts   ON audit_log (ts);
CREATE INDEX IF NOT EXISTS idx_audit_type ON audit_log (event_type);

-- ── SMS log (Cellcast send + inbound/DLR — spec #14/#16) ────────────
-- Recipient phone is PII; the nightly purge job trims rows older than the
-- configured SMS retention window.
CREATE TABLE IF NOT EXISTS sms_log (
  id          INTEGER PRIMARY KEY AUTOINCREMENT,
  direction   TEXT NOT NULL,   -- outbound | inbound | dlr
  recipient   TEXT,            -- destination (outbound) or sender (inbound)
  status      TEXT,            -- queued | sent | delivered | failed | received | skipped
  provider_id TEXT,            -- Cellcast message id, for correlation
  booking_id  TEXT,            -- optional link to pending_bookings.id
  error       TEXT,
  created_at  TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_sms_status  ON sms_log (status);
CREATE INDEX IF NOT EXISTS idx_sms_created ON sms_log (created_at);

-- ── System state (key/value: connection health, sync cursors) ───────
CREATE TABLE IF NOT EXISTS system_state (
  key        TEXT PRIMARY KEY,
  value      TEXT,
  updated_at TEXT NOT NULL
);
